return {
    { "LazyVim/LazyVim", opts = { colorscheme = "tokyonight-storm" } },
    -- { "maxmx03/dracula.nvim" },
    { "github/copilot.vim" },
    { "nvim-telescope/telescope-dap.nvim" },
    { "saecki/crates.nvim", dependencies = { { "nvim-lua/plenary.nvim" } } },
    { "stevearc/dressing.nvim" },
    { "theHamsta/nvim-dap-virtual-text" },
    { "tpope/vim-abolish" },
    { "tpope/vim-commentary" },
    { "tpope/vim-endwise" },
    { "tpope/vim-fugitive" },
    { "tpope/vim-repeat" },
    { "tpope/vim-speeddating" },
    { "triglav/vim-visual-increment" },
}
